name: flutter_aliyun_slider
description: 适用于 Flutter 的阿里云人机验证插件，兼容客户端和 WEB 端
version: 1.1.5
homepage: https://github.com/sharebravery/flutter_aliyun_slider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.flutter_aliyun_slider
        pluginClass: FlutterAliyunCaptchaPlugin
      ios:
        pluginClass: FlutterAliyunCaptchaPlugin

  assets:
    - assets/captcha.html
